const CARDS = [
  {
    number: 1,
    title: "The First Light",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 1 - The First Light.jpeg",
    purpose: "Thank you for your essence and all that you have endured across every season of your life. You are now being asked to rise gently into your own light through trust, awareness, and remembrance. This is the beginning of returning home to yourself.",
    meaning: "You were never created for a life of shrinking, silence, or disconnection from your truth. This energy asks you to trust that even when life felt uncertain, there was still movement taking place beneath the surface. Trust is not only external. It is the rebuilding of trust within yourself — trusting your voice, your feelings, your path, your timing, and your ability to rise again after disappointment or pain. The past has shaped you, but it does not define the fullness of who you are becoming.  You are allowed to begin again without shame. You are allowed to move forward without carrying every old version of yourself with you. There is light returning to places within you that once felt forgotten.",
    mantra: "I activate now through the power of the ascended mothers and into my dragon power",
  },
  {
    number: 2,
    title: "The Living Channel",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 2 - The Living Channel.jpeg",
    purpose: "You have spent enough lifetimes questioning your worth. This card arrives to remind you that your voice, energy, and presence carry far more power than you have allowed yourself to believe.",
    meaning: "There is a part of you that has always known you were meant for more. Not from ego, but from remembrance. You feel deeply, sense beyond words, and carry gifts that were never meant to stay hidden. This energy asks you to stop doubting your inner voice and trust what naturally flows through you. The moment you stop shrinking yourself, life begins responding differently. Synchronicities increase, clarity returns, and your path starts opening with greater ease.",
    mantra: "I allow divine wisdom, power, and creation to move freely through me.",
  },
  {
    number: 3,
    title: "The Inner Knowing",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 3 - The Inner Knowing.jpeg",
    purpose: "You already hold the answers you keep searching for externally. This card arrives to guide you back toward the wisdom, intuition, and truth quietly living within you.",
    meaning: "So much of your life has been spent seeking confirmation, signs, or permission before trusting yourself. Yet your soul has always been speaking softly beneath the noise. You feel things before they happen. You sense truth beyond appearances. This energy asks you to become still enough to hear yourself again. Not every answer needs logic, and not every path can be explained before it unfolds. Trust the quiet pull within your spirit. Your intuition is not confusion — it is remembrance returning to you.",
    mantra: "I trust the sacred wisdom within me and allow my intuition to guide my path.",
  },
  {
    number: 4,
    title: "The Radiant Womb",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 4 - The Radiant Womb.jpeg",
    purpose: "Thank you for all you have carried, birthed, nourished, and loved. It is now time to receive as deeply as you have given.",
    meaning: "For so long you have poured yourself into others, into dreams, into survival, into becoming. Yet creation was never only about giving life outwardly. There are parts of you asking to be nurtured too. Not everything blooms through force. Some things unfold through softness, rest, and allowing yourself to be held by life itself. Allow yourself to remember that you too are sacred ground. The energy you pour into others was never meant to leave you empty. Rest is not weakness, receiving is not selfishness, and your own heart is deserving of the same tenderness you freely give.",
    mantra: "I receive the abundance, love, and creation already growing within me. I honor my sacred essence and allow life to nourish me in return.",
  },
  {
    number: 5,
    title: "The Sacred Structure",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 5 - The Sacred Structure.jpeg",
    purpose: "Within your spirit lives an ancient strength that was built to stand steady through every storm.",
    meaning: "You were never created to live in chaos forever. Beneath the uncertainty lives a version of you that knows exactly where to place the stones beneath your feet. Boundaries are not walls around your heart; they are sacred architecture protecting what matters most. There is wisdom in standing firmly without becoming rigid. Strength does not ask you to carry the weight of the world; it asks you to create a foundation where your spirit feels safe enough to grow.",
    mantra: "I stand rooted within truth and build from sacred strength. I create foundations that support the highest expression of who I am.",
  },
  {
    number: 6,
    title: "The Path of Alignment",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 6 - The Path of Alignment.jpeg",
    purpose: "Not every road is yours to walk; your soul already knows the rhythm meant for you.",
    meaning: "There comes a moment where outside voices become too loud and the heart grows tired of carrying expectations. Somewhere beneath the noise your truth has remained untouched. Your journey was never meant to be a copy of another's path. It was meant to become your own sacred unfolding. You do not need permission to honor what resonates within your soul. The more you trust your inner compass, the more life begins unfolding in ways that feel natural rather than forced.",
    mantra: "I honor the truth that lives within my soul. I walk in harmony with the path that was always meant for me.",
  },
  {
    number: 7,
    title: "The Harmonic Union",
    pillar: "PILLAR I - THE AWAKENING",
    image: "/cards/No 7 - The Harmonic Union.jpeg",
    purpose: "Every choice you make becomes a conversation between your soul and your future.",
    meaning: "Love is not only found in another person. It lives in the moments where you choose yourself, honor your truth, and stop abandoning parts of who you are. Real union begins when the mind, heart, and spirit stop pulling in different directions and begin walking together. Every decision becomes an act of self-love or self-abandonment. Listen to what creates peace within your spirit and choose what allows your heart to breathe.",
    mantra: "I choose what honors my heart and aligns with my soul. I create harmony within and around me.",
  },
  {
    number: 8,
    title: "The Forward Current",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 8 - The Forward Current.jpeg",
    purpose: "The road ahead is opening because you are no longer the person who once feared walking it.",
    meaning: "There were times you stood at the edge of your own life waiting for certainty before taking a step. Yet movement itself creates momentum. You have already survived days you thought would break you. Trust your feet; they remember the way forward. There is no need to wait for perfect certainty before moving. Life meets movement with movement, and every step taken in trust creates its own momentum.",
    mantra: "I move with purpose and trust the direction of my soul. I release fear and embrace the journey before me.",
  },
  {
    number: 9,
    title: "The Gentle Power",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 9 - The Gentle Power.jpeg",
    purpose: "The deepest strength within you was never force — it was love.",
    meaning: "You have mistaken survival for strength for far too long. Strength is not the tightening of fists or carrying everything alone. It is the quiet courage to remain open after disappointment, to remain kind after hardship, and to keep your heart alive after every season that tried to close it. Your softness has never been a flaw. It is the very thing that has carried you through moments that force alone never could.",
    mantra: "I honor the quiet strength living within my heart. I stand in compassion, courage, and grace.",
  },
  {
    number: 10,
    title: "The Quiet Light",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 10 - The Quiet Light.jpeg",
    purpose: "There are answers waiting for you in places noise cannot reach.",
    meaning: "You do not need to rush toward clarity. The soul rarely shouts; it whispers. There are moments where stepping away from the world is not loneliness but sacred remembering. In stillness, pieces of yourself return home. You are not lost in the stillness. You are rediscovering pieces of yourself that were waiting patiently to be heard.",
    mantra: "I trust the wisdom waiting within my stillness. I allow my inner light to gently guide my way.",
  },
  {
    number: 11,
    title: "The Sacred Cycle",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 11 - The Sacred Cycle.jpeg",
    purpose: "Nothing within existence stands still; every ending quietly prepares the doorway for a beginning.",
    meaning: "You may be holding tightly to what once felt familiar because change can feel like standing on shifting ground. Yet every season of your life has shaped you into who you are now. The wheel does not move to punish you; it moves because life itself is always becoming. What is leaving your life is not always loss. Sometimes it is simply completion making space for the next chapter of your becoming.",
    mantra: "I trust the sacred unfolding of every season of my journey. I welcome change as a pathway into new beginnings.",
  },
  {
    number: 12,
    title: "The Clear Balance",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 12 - The Clear Balance.jpeg",
    purpose: "Every choice, action, and truth carries an energy of return. What is being asked of you now is not punishment or reward, but sacred honesty with yourself.",
    meaning: "Life is placing a mirror into your hands, asking for honesty before action. The scales before you are not measuring perfection; they are revealing where energy has been overextended, where truth has been silenced, and where your soul has quietly asked for harmony. True balance arrives when your choices begin reflecting the person you are becoming. Balance is not something you force into place. It is something you return to, again and again, through awareness. Even small corrections in how you speak, choose, and respond begin to restore your inner steadiness.",
    mantra: "I honor truth within myself. I create balance through conscious choice, clear intention, and alignment with my highest path.",
  },
  {
    number: 13,
    title: "The Sacred Pause",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 13 - The Sacred Pause.jpeg",
    purpose: "Not every moment asks for movement; some moments ask for surrender and a new way of seeing.",
    meaning: "Movement is not the only sign of progress. In this still space, unseen shifts are taking place beneath the surface, much like roots strengthening beneath the earth before new life emerges. Release the pressure to force answers. What is meant for you is already moving toward you. In this stillness, you may notice what you’ve been avoiding or rushing past. Nothing is lost in the pause — it is where clarity quietly reorganizes itself.",
    mantra: "I surrender control and trust the wisdom unfolding within stillness. I allow new perspectives to reveal themselves with grace.",
  },
  {
    number: 14,
    title: "The Light of Transformation",
    pillar: "PILLAR II - STABILISATION",
    image: "/cards/No 14 - The Light of Transformation.jpeg",
    purpose: "Thank you for all that you have carried until now. Something within you has completed its journey and is ready to become something new.",
    meaning: "Endings often arrive wearing the disguise of loss, and for a moment the heart can struggle to understand why something familiar must fall away. Yet life has never asked you to remain the same version of yourself forever. There are old identities, fears, wounds, and stories that have loved and protected you for as long as they could. Their work is complete now. Do not fear what is leaving, because what is leaving is creating space for what is waiting to arrive. You are not ending; you are becoming.",
    mantra: "I release with gratitude and welcome transformation with trust. I rise renewed into the next expression of who I am.",
  },
  {
    number: 15,
    title: "The Flow of Harmony",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 15 - The Flow of Harmony.jpeg",
    purpose: "Your soul remembers the rhythm of peace even when life feels fragmented.",
    meaning: "There is a sacred place where effort and surrender meet, where giving and receiving exist in harmony, and where the heart no longer needs to pull in opposite directions. You were never meant to live at the extremes of exhaustion and emptiness. Life is inviting you back toward your natural rhythm. Trust that not everything requires urgency. Some things unfold most beautifully when they are allowed to flow.",
    mantra: "I move in harmony with life. I welcome balance, peace, and divine flow into every part of my being.",
  },
  {
    number: 16,
    title: "The Revealed Illusion",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 16 - The Revealed Illusion.jpeg",
    purpose: "Not everything that appears before you carries truth; some things arrive to teach discernment and deeper self-trust.",
    meaning: "Fog can make familiar paths appear uncertain, and fear can make shadows seem larger than they truly are. Look gently beneath the surface of what you are feeling. What once felt confusing may simply be asking you to trust your inner vision over old fears and inherited stories. What feels uncomfortable to see is often what frees you the most. Truth does not harm you — it removes what was already harming you.",
    mantra: "I trust the wisdom beneath illusion. I see clearly, feel deeply, and allow truth to rise within me.",
  },
  {
    number: 17,
    title: "The Shattering Light",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 17 - The Shattering Light.jpeg",
    purpose: "What falls away now was never sent to destroy you; it was only asked to release what could no longer contain your becoming.",
    meaning: "Lightning never strikes to punish the sky; it illuminates what was hidden. Cracks appearing in old foundations are creating openings for truth to enter. Allow what no longer reflects your spirit to fall away with grace rather than resistance. What breaks open now is not your destruction, but your awakening. Even in collapse, there is a deeper intelligence guiding you toward truth.",
    mantra: "I release what no longer holds my truth. I welcome sacred change and rise stronger through transformation.",
  },
  {
    number: 18,
    title: "The Guiding Light",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 18 - The Guiding Light.jpeg",
    purpose: "Even after the darkest nights, there has always been a light within you quietly leading you home.",
    meaning: "You have walked through seasons that asked much of your heart. There were moments where hope felt distant and where you questioned whether your path was still unfolding as it should. Yet your spirit never stopped carrying its own light. Healing does not ask you to become someone else; it asks you to remember who you have always been beneath pain and fear. The future has not forgotten you. Your dreams have not abandoned you. Allow hope to enter again.",
    mantra: "I trust the light within me. I receive healing, guidance, and hope into every part of my journey.",
  },
  {
    number: 19,
    title: "The Dreaming Light",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 19 - The Dreaming Light.jpeg",
    purpose: "Your inner world holds messages, symbols, and wisdom waiting to be understood rather than feared.",
    meaning: "Not all wisdom arrives through logic or explanation. Some truths drift through dreams, symbols, emotions, and quiet moments that brush against the soul and leave a feeling of recognition. Your spirit is speaking in its own language now, asking you to listen with your heart rather than your mind alone. Hidden waters often hold the deepest reflections, and what feels distant or unclear today may become profound understanding tomorrow. Trust the whispers that return repeatedly. Your soul remembers what your conscious mind is still learning to understand.",
    mantra: "I trust the wisdom moving through my inner world. I honor the messages of my spirit and intuition.",
  },
  {
    number: 20,
    title: "The Living Sun",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 20 - The Living Sun.jpeg",
    purpose: "You were never created to spend your life hiding your joy, your light, or your truth.",
    meaning: "There is a version of you untouched by fear, disappointment, and old stories. A part of you still remembers how to laugh without reason, create without doubt, and shine without apology. Life is asking you to stop dimming yourself for spaces unable to receive your brilliance. Joy is not something you earn after suffering; it is part of your natural state of being. The sun doesn't ask permission to shine or be brilliant, it does it without permission.",
    mantra: "I honor my light and allow my joy to rise freely. I shine as the fullest expression of who I am.",
  },
  {
    number: 21,
    title: "The Awakening Pulse",
    pillar: "PILLAR III - BREAKTHROUGH",
    image: "/cards/No 21 - The Awakening Pulse.jpeg",
    purpose: "Something ancient within your soul is stirring and calling you toward a deeper remembrance of who you are.",
    meaning: "Something within you has begun stirring beneath the surface, like the first heartbeat of a new beginning calling your spirit forward. Old ways of thinking, feeling, and existing may suddenly feel too small because your soul is expanding beyond them. This is not restlessness; it is remembrance. You are hearing the quiet call of your own becoming. Trust the energy rising within you, because what is awakening is not foreign to you — it is a deeper part of yourself returning home.",
    mantra: "I answer the sacred call within me. I awaken fully into truth, purpose, and remembrance.",
  },
  {
    number: 22,
    title: "The Infinite Integration",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 22 - The Infinite Integration.jpeg",
    purpose: "Honour how far you have travelled, for every experience has become part of the wisdom you now carry.",
    meaning: "You are no longer standing where you once began. Every lesson, heartbreak, triumph, and transformation has woven itself into who you are becoming. Nothing was wasted. Even moments that once felt painful have become threads within your story. Completion is not an ending; it is the gathering together of everything you have learned before stepping into something new. The mastery that began, will complete once you understand the stillness of your own essence.",
    mantra: "I honor my journey and embrace the wholeness of all I have become. I stand complete within my sacred unfolding.",
  },
  {
    number: 23,
    title: "The Sacred Mirror",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 23 - The Sacred Mirror.jpeg",
    purpose: "Thank you for carrying wounds, burdens, and silent tears through lifetimes. Today you are being asked to see yourself through the eyes of compassion rather than judgment.",
    meaning: "Stand before yourself with the same tenderness you would offer a child who had forgotten their worth. Your scars are not evidence of brokenness; they are proof of the journeys your heart survived. Compassion becomes the bridge returning you back to yourself. What you see in others often reflects something unspoken within you. This awareness is not for judgment, but for deeper understanding and integration.",
    mantra: "I see myself through the eyes of grace. I receive compassion, healing, and love into every part of my being.",
  },
  {
    number: 24,
    title: "The Threshold of Becoming",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 24 - The Threshold of Becoming.jpeg",
    purpose: "You are standing at the doorway between who you were and who your spirit is ready to become.",
    meaning: "There comes a moment where old identities begin feeling too small for the soul that is awakening within you. One foot may still stand in familiarity while the other senses something new calling from beyond the horizon. Do not fear the unknown space between endings and beginnings. Great transformation often begins in sacred uncertainty. Trust that what is unfolding has been preparing itself within you long before this moment arrived.",
    mantra: "I honor the sacred doorway before me. I step forward with trust into my becoming.",
  },
  {
    number: 25,
    title: "The Soul Retrieval",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 25 - The Soul Retrieval.jpeg",
    purpose: "Pieces of your spirit are returning home after being scattered through pain, fear, and survival.",
    meaning: "There were moments where parts of you became hidden beneath heartbreak, disappointment, or the need to protect yourself. Yet your soul has never forgotten where those pieces belong. You are being called back into wholeness. Gently gather the parts of yourself you abandoned to be accepted, loved, or understood. Nothing within you was ever truly lost; it has only been waiting to be welcomed home.",
    mantra: "I lovingly call every part of myself back into wholeness. I return home to my sacred essence.",
  },
  {
    number: 26,
    title: "The Divine Catalyst",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 26 - The Divine Catalyst.jpeg",
    purpose: "The spark that awakens the heart often arrives to remind you of your own power to create and transform.",
    meaning: "Life sometimes sends people, moments, or experiences that shake something dormant awake within you. They do not arrive to complete you; they arrive to reveal you to yourself. Passion, joy, beauty, and creation are not distractions from your path — they are life moving through you. Allow your heart to remember its rhythm and trust what it is asking you to express. You weren't created to play small, your purpose is extortionary, believe it.",
    mantra: "I awaken the sacred fire within me. I create, love, and expand through my divine essence.",
  },
  {
    number: 27,
    title: "The Burning Illusion",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 27 - The Burning Illusion.jpeg",
    purpose: "Not everything you believed about yourself was ever the truth of who you are.",
    meaning: "Fire does not always destroy; sometimes it purifies. Old labels, false beliefs, and inherited expectations are dissolving because they can no longer hold the truth of who you are becoming. Beneath the ashes stands your authentic self. What cannot survive truth will dissolve in its presence. You are not losing yourself — you are releasing distortion. You are rising from ember into a celestial sentient being.",
    mantra: "I release false stories and stand within the truth of my soul. I rise free and whole.",
  },
  {
    number: 28,
    title: "The Celestial Alignment",
    pillar: "PILLAR IV - RESTRUCTURE",
    image: "/cards/No 28 - The Celestial Alignment.jpeg",
    purpose: "Within every season of uncertainty there exists a greater harmony quietly guiding your journey.",
    meaning: "Even when clouds cover the night sky, the stars remain in their places. Life is quietly arranging people, timing, and experiences in ways the mind cannot always understand. Trust that your path is held within a greater harmony. You begin to feel when something is in harmony with you, even without explanation. This quiet sense of rightness becomes your new form of guidance. Trust it, it has never failed.",
    mantra: "I trust the divine rhythm of my journey. I am supported, guided, and held in sacred love.",
  },
  {
    number: 29,
    title: "The Shadow Alchemist",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 29 - The Shadow Alchemist.jpeg",
    purpose: "Within the places you once feared lives medicine waiting to be transformed into wisdom.",
    meaning: "The parts of yourself hidden in darkness were never waiting for rejection; they were waiting for understanding. Healing begins the moment you stop standing against yourself and begin listening to what those hidden places have been trying to teach you. What you once rejected becomes the very source of your strength. Nothing within you is wasted — even your shadow carries wisdom when met with awareness.",
    mantra: "I honor every part of my journey. I transform shadow into wisdom, strength, and sacred power.",
  },
  {
    number: 30,
    title: "The Quiet Knowing",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 30 - The Quiet Knowing.jpeg",
    purpose: "There are truths your soul recognized long before your mind searched for proof.",
    meaning: "You have questioned yourself enough. Beneath overthinking, uncertainty, and the need for confirmation lives a deeper awareness that has always walked beside you. You have felt it in moments where something simply did not feel right, and in moments where your heart knew before your eyes could see. Your inner vision was never given to confuse you; it was given to guide you. Wisdom does not always arrive loudly. Sometimes truth enters softly and asks only to be trusted.",
    mantra: "I trust the wisdom already living within me. I see beyond illusion and honor my inner truth.",
  },
  {
    number: 31,
    title: "The Sacred Choice",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 31 - The Sacred Choice.jpeg",
    purpose: "Every choice becomes a doorway, and every doorway carries the power to reshape your journey.",
    meaning: "Doorways rarely announce where they lead before you step through them. One path may feel safe while another awakens your spirit. Let your heart become the compass and your truth become the direction. Some choices change direction, while others change identity. This moment asks you to trust not what is easiest, but what feels deeply aligned within your spirit. Some paths remain hidden until the student is ready to be unlocked.",
    mantra: "I choose from the wisdom of my soul. I walk through sacred doorways with trust and courage.",
  },
  {
    number: 32,
    title: "The Fractured Mask",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 32 - The Fractured Mask.jpeg",
    purpose: "What has been hidden beneath survival is ready to be seen without fear.",
    meaning: "There were masks you wore to protect yourself, to belong, and to survive moments that asked more from you than you thought you could give. Yet carrying what is not truly you becomes heavy over time. Cracks are appearing now, not to expose weakness, but to release what no longer belongs to your spirit. There is freedom in being seen as you are.",
    mantra: "I release false identities and honor the truth of my spirit. I stand whole within my authenticity.",
  },
  {
    number: 33,
    title: "The River of Remembrance",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 33 - The River of Remembrance.jpeg",
    purpose: "Your soul carries ancient wisdom waiting to rise into awareness once more.",
    meaning: "A current is moving through your spirit, carrying forgotten wisdom back toward the shore of awareness. Certain dreams, emotions, and moments of recognition are not random; they are invitations into deeper remembering. Allow these memories of the soul to rise without needing to control or explain them. What returns now carries medicine, wisdom, and pieces of yourself ready to be reclaimed.",
    mantra: "I welcome the wisdom carried within my soul. I remember who I have always been.",
  },
  {
    number: 34,
    title: "The Cosmic Weaver",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 34 - The Cosmic Weaver.jpeg",
    purpose: "Nothing within existence stands alone; every thread is woven into a greater design.",
    meaning: "Threads that once appeared disconnected are beginning to reveal their design. Every experience, even the painful ones, has become part of a larger tapestry that your soul has been creating all along. Nothing has been wasted, even the moments you once wished had never happened. Seen from a higher perspective, every thread has contributed to the masterpiece still unfolding before you.",
    mantra: "I trust the sacred design unfolding through my life. I honor the wisdom woven into my journey.",
  },
  {
    number: 35,
    title: "The Unwritten Path",
    pillar: "PILLAR V - MEMORY WEAVING",
    image: "/cards/No 35 - The Unwritten Path.jpeg",
    purpose: "Not every chapter of your life was meant to be written by your past.",
    meaning: "You are standing before open space, a place where old stories no longer define what comes next. While uncertainty can feel uncomfortable, it also carries possibility. Your spirit is not asking you to repeat what has already been lived. There is freedom in stepping beyond expectation and allowing a new story to emerge.",
    mantra: "I step beyond limitation and trust the path unfolding before me. I create from truth and possibility.",
  },
  {
    number: 36,
    title: "The Sacred Undoing",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 36 - The Sacred Undoing.jpeg",
    purpose: "Sometimes life removes what the soul has already outgrown.",
    meaning: "Hands cannot receive something new while gripping tightly to what is already leaving. Life is gently untying knots that no longer belong within your journey, creating space for a truer expression of yourself to emerge. Release does not always arrive gently, but it always creates movement. Trust that what leaves your hands now is making room for what your soul has been quietly calling toward itself.",
    mantra: "I trust the sacred release taking place within my life. I allow transformation to guide my becoming.",
  },
  {
    number: 37,
    title: "The Eternal Flame",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 37 - The Eternal Flame.jpeg",
    purpose: "Within you lives a fire that cannot be extinguished by endings, loss, or change.",
    meaning: "You have entered fires before and emerged carrying wisdom you did not possess before walking through them. There is a part of you untouched by hardship and untouched by fear. This flame does not exist to consume you; it exists to reveal your resilience and your truth. Ashes are not endings. They are preparation for rebirth.",
    mantra: "I rise through every transformation renewed, powerful, and illuminated by my eternal flame.",
  },
  {
    number: 38,
    title: "The Heart Awakening",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 38 - The Heart Awakening.jpeg",
    purpose: "Life returns to the places within you that once felt closed or forgotten.",
    meaning: "A closed flower does not remain closed forever. Layers built from protection and past hurt are beginning to soften, allowing life to touch places within you that have waited patiently for warmth, connection, and love once more. The heart was never created to remain hidden beneath armor forever. Love, joy, connection, and truth are beginning to find their way back home within you.",
    mantra: "I open my heart to life, truth, and sacred connection. I allow love to move freely through me.",
  },
  {
    number: 39,
    title: "The Between Worlds",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 39 - The Between Worlds.jpeg",
    purpose: "You are standing between endings and beginnings, between who you were and who you are becoming.",
    meaning: "The space between worlds can feel uncertain because the old no longer fits and the new has not fully arrived. Yet this threshold carries its own wisdom. You are not lost here. You are transitioning. Trust that unseen movement is taking place even when clarity has not yet appeared. You may feel in-between who you were and who you are becoming. This space is not confusion — it is transition preparing you for integration.",
    mantra: "I trust the sacred space of transformation. I move between worlds with peace and trust.",
  },
  {
    number: 40,
    title: "The Living Temple",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 40 - The Living Temple.jpeg",
    purpose: "Your body, spirit, and soul were never separate from the sacred.",
    meaning: "You have searched for wisdom in distant places while carrying a living sanctuary within you all along. Your body remembers, your spirit speaks, and your heart holds truths waiting to be heard. Honour yourself as sacred ground. The divine was never outside of you; it has always lived through you. Your body is not separate from your healing — it is part of it. How you care for yourself physically becomes part of how you honor your life.",
    mantra: "I honor my body, spirit, and soul as sacred. I awaken the living wisdom within me.",
  },
  {
    number: 41,
    title: "The Visionary Seed",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 41 - The Visionary Seed.jpeg",
    purpose: "Within you lives a seed of possibility that arrived long before you remembered who you were becoming.",
    meaning: "Some dreams enter your heart with unusual persistence, returning repeatedly even when logic asks you to let them go. Certain visions do not arrive to entertain the mind; they arrive because they carry a future version of you waiting to be expressed. Seeds do not question whether they contain life — they simply trust the intelligence already living within them. Honour the ideas, inspirations, and quiet longings calling your spirit. What feels small today may already contain entire worlds waiting to unfold.",
    mantra: "I nurture the visions placed within my soul. I trust the divine intelligence growing through me.",
  },
  {
    number: 42,
    title: "The Inner Throne",
    pillar: "PILLAR VI - EMBODIMENT",
    image: "/cards/No 42 - The Inner Throne.jpeg",
    purpose: "Strength was never meant to be measured by what you carry, but by what you have learned to overcome.",
    meaning: "Life may have asked much of your spirit and placed mountains before you that once felt impossible to climb. Yet hidden beneath every challenge was the discovery of your own power. The throne before you was never something to conquer outside of yourself; it always existed within. Stand in your truth without shrinking and honor the courage that has brought you here. You were not shaped by struggle alone, but by your decision to keep rising.",
    mantra: "I stand firmly within my strength. I honor the power and wisdom living within me.",
  },
  {
    number: 43,
    title: "The Threads of Fate",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 43 - The Threads of Fate.jpeg",
    purpose: "Invisible threads are moving through your life, connecting moments, choices, and souls in ways not yet fully seen.",
    meaning: "A meeting, a delay, a goodbye, or an unexpected turn can appear random when seen from only one moment in time. Yet the tapestry of life is woven far beyond what the eyes immediately understand. Some threads arrive to remain while others arrive to redirect your journey. Trust that every experience has carried meaning, even when its purpose revealed itself much later. What connects your experiences is not randomness, but unfolding meaning. Even what felt disconnected begins to reveal its place in your becoming.",
    mantra: "I trust the sacred threads woven through my journey. I honor the unfolding design of my life.",
  },
  {
    number: 44,
    title: "The Tides Within",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 44 - The Tides Within.jpeg",
    purpose: "Your emotions are not obstacles on your path; they are currents carrying messages from your deepest self.",
    meaning: "The ocean never apologizes for its changing tides. Calm waters, rising waves, and hidden depths all belong to its nature. The same truth exists within you. Feelings do not arrive to weaken your spirit; they arrive to reveal what seeks understanding, healing, and expression. Honour what moves within you without becoming consumed by it. Wisdom often waits beneath the surface.",
    mantra: "I honor the tides moving within me. I allow my emotions to become wisdom and guidance.",
  },
  {
    number: 45,
    title: "The Radiant Self",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 45 - The Radiant Self.jpeg",
    purpose: "Your light was never meant to remain hidden behind fear, doubt, or the expectations of others.",
    meaning: "Sunlight does not ask permission before it rises. It simply shines according to its nature. Somewhere along your journey, parts of your brilliance may have become dimmed to fit spaces unable to receive them. Yet your gifts, joy, creativity, and truth were never meant to be reduced. Allow yourself to stand fully within your own presence and remember that authenticity is its own form of radiance.",
    mantra: "I honor the light within me. I shine as the fullest expression of my soul.",
  },
  {
    number: 46,
    title: "The Soul Architect",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 46 - The Soul Architect.jpeg",
    purpose: "Everything you are becoming is being shaped through the choices, intentions, and energies you create today.",
    meaning: "Builders first see the vision before the structure appears. In the same way, your soul has always carried an inner blueprint waiting to be brought into form. Every thought, action, and decision places another stone within the life you are creating. You are not merely reacting to life; you are participating in its design. Build from truth and create from alignment.",
    mantra: "I consciously create from the wisdom of my soul. I build a life aligned with my highest truth.",
  },
  {
    number: 47,
    title: "The Return of Presence",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 47 - The Return of Presence.jpeg",
    purpose: "You have travelled through separation, longing, and forgetting; now your soul is remembering the sacredness of returning home to yourself.",
    meaning: "So much energy can be spent revisiting the past or reaching toward the future that the beauty of this moment becomes hidden. Presence is not simply being here physically; it is allowing your heart, spirit, and essence to fully arrive. Within this space lives love without conditions, truth without fear, and peace without striving. The sacred has never existed in some distant destination waiting for you to reach it. It has always been waiting for you in the quiet space of now. Come back to your breath, your body, your heart, and the living miracle of your own existence.",
    mantra: "I return fully into the sacredness of this moment. I am present, whole, and connected to divine love.",
  },
  {
    number: 48,
    title: "The Infinite Heart",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 48 - The Infinite Heart.jpeg",
    purpose: "The heart was never created to live only through survival; it was created to experience the fullness of life.",
    meaning: "Within your spirit lives an ocean without edges, a place where joy, passion, creativity, love, and connection move freely. Life may have taught you to close certain doors within yourself for protection, yet the heart was never designed to remain confined. Expansion begins when you give yourself permission to feel deeply and live authentically. Love is not a limited resource to be earned or measured. It moves endlessly through existence, asking only to be experienced and shared.",
    mantra: "I open myself to the limitless expression of love. My heart expands beyond fear and into sacred connection.",
  },
  {
    number: 49,
    title: "The Sophia Spark",
    pillar: "PILLAR VII - TRANSCENDENCE",
    image: "/cards/No 49 - The Sophia Spark.jpeg",
    purpose: "Before every star, every breath, and every beginning, the spark of creation already existed within the silence.",
    meaning: "Something sacred lives within you that cannot be reduced by circumstances, forgotten by time, or diminished by fear. It is the quiet flame that has continued to rise after every challenge, the whisper that kept calling you forward even in uncertain seasons. This spark does not ask you to become something else; it asks you to remember. Creation itself moves through your thoughts, your dreams, your love, and your becoming. You are not separate from the intelligence of life; you are an expression of it.",
    mantra: "I awaken the Sophia Spark within me. I create, expand, and embody the infinite wisdom of my soul.",
  },
];

/**
 * Fisher-Yates Shuffle
 * Guaranteed high-entropy variety for 3-card readings.
 */
function shuffle(array) {
  let currentIndex = array.length,  randomIndex;
  while (currentIndex !== 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex], array[currentIndex]]; module.exports = CARDS;