import LegalPage, { Section, P, Ul, Li } from "./LegalPage.jsx";

const CONTACT_EMAIL = "holistic@963.co.za";

export default function LicensingScreen({ onBack }) {
  return (
    <LegalPage title="Licensing & IP Protection" subtitle="Intellectual Property Notice" onBack={onBack}>

      <Section title="Copyright Notice">
        <P>&copy; 2026 Tessera Lumen. All rights reserved.</P>
        <P>All content, artwork, text, and systems within the Tessera Lumen platform are the exclusive intellectual property of Tessera Lumen and are protected under South African and international copyright law.</P>
      </Section>

      <Section title="Card Artwork">
        <P>All 49 original tarot card artworks are commissioned, original works owned exclusively by Tessera Lumen. These artworks are:</P>
        <Ul>
          <Li>Protected by copyright from the date of creation</Li>
          <Li>Licensed for viewing within the Tessera Lumen platform only</Li>
          <Li>Not available for download, reproduction, or redistribution</Li>
          <Li>Not licensed for use in any other application, publication, or medium</Li>
          <Li>Watermarked to identify unauthorised reproduction</Li>
        </Ul>
        <P>Any unauthorised reproduction, distribution, or commercial use of the card artwork constitutes copyright infringement and may result in legal action.</P>
      </Section>

      <Section title="Written Content">
        <P>All written content within the Tessera Lumen oracle system is original literary work, including:</P>
        <Ul>
          <Li>Card titles and naming conventions</Li>
          <Li>Purpose statements for each card</Li>
          <Li>Meaning and embodiment descriptions</Li>
          <Li>Mantras and affirmations</Li>
          <Li>Pillar framework and structural system</Li>
          <Li>All UI text, descriptions, and oracle language</Li>
        </Ul>
        <P>This written content may not be reproduced, adapted, translated, or published without express written permission from Tessera Lumen.</P>
      </Section>

      <Section title="Oracle System">
        <P>The Tessera Lumen oracle system  including the 7-pillar framework, card sequencing, reading methodology, and spiritual architecture  is an original proprietary system. It may not be replicated, adapted, or used as the basis for any other oracle, tarot, or guidance system without written authorisation.</P>
      </Section>

      <Section title="Downloadable Reading Content">
        <P>Personal reading summaries generated by the platform are licensed to the individual user for personal, non-commercial use only. These documents:</P>
        <Ul>
          <Li>May be retained for personal spiritual reference</Li>
          <Li>May be shared privately with individuals</Li>
          <Li>May not be published, sold, or distributed commercially</Li>
          <Li>May not be used to represent or replicate the Tessera Lumen system</Li>
          <Li>Remain subject to Tessera Lumen copyright notices embedded within</Li>
        </Ul>
      </Section>

      <Section title="Trademark">
        <P>The name &ldquo;Tessera Lumen&rdquo;, the tagline &ldquo;Oracle of the Soul&rdquo;, and associated logos and visual identity are trademarks of Tessera Lumen. These marks may not be used in connection with any product or service without prior written consent.</P>
      </Section>

      <Section title="Reporting Infringement">
        <P>If you become aware of any unauthorised use of Tessera Lumen intellectual property, please contact us directly. We take intellectual property protection seriously and will act promptly on credible reports of infringement.</P>
        <P><a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#D4AF37", fontFamily: "Cinzel, serif", letterSpacing: "0.1em" }}>{CONTACT_EMAIL}</a></P>
      </Section>

    </LegalPage>
  );
}
